version: '3.8'

services:
  server:
    image: 'registry.gitlab.com/hapi_p/bocachica-backend'
    restart: always
    environment:
      DB_HOST: 'postgres'
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_DATABASE: $DB_DATABASE
      QUEUE_REDIS_URL: redis://redis:6379
      SOLANA_ENDPOINT_URL:
      CORS_ORIGINS:
      SOLANABEACH_API_URL:
      SOLANABEACH_API_KEY:
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname == bocachica]
  postgres:
    image: 'postgres:13-alpine'
    restart: always
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_DB: $DB_DATABASE
      POSTGRES_PASSWORD: $DB_PASSWORD
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname == bocachica]
  redis:
    image: 'redis:6-alpine'
    restart: always
    volumes:
      - redis-data:/data
    ports:
      - '6379:6379'
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname == bocachica]

volumes:
  postgres-data:
  redis-data:
