version: '3.8'

services:
  server:
    build: .
    restart: always
    environment:
      DB_HOST: 'postgres'
      DB_USER: 'bocachica'
      DB_PASSWORD: 'bocachica'
      DB_DATABASE: 'bocachica'
    ports:
      - '3000:3000'
  postgres:
    image: 'postgres:13-alpine'
    restart: always
    environment:
      POSTGRES_USER: 'bocachica'
      POSTGRES_DB: 'bocachica'
      POSTGRES_PASSWORD: 'bocachica'
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  redis:
    image: 'redis:6-alpine'
    restart: always
    ports:
      - '6379:6379'
